events { worker_connections 1024; }
http {
    upstream person_service { server person-service-green:5004; }
    upstream location_service { server location-service-green:5005; }
    upstream notification_service { server notification-service-green:5006; }
    upstream frontend_service { server frontend:3000; }
    server {
        listen 80;
        location /api/missingpeople { proxy_pass http://person_service/api/missingpeople; }
        location /api/foundlocation { proxy_pass http://location_service/api/foundlocation; }
        location /api/notifications { proxy_pass http://notification_service/api/notifications; }
        location / { proxy_pass http://frontend_service; }
    }
}
